#!/bin/bash

echo "🚂 Deploying Sparsh Clinic to Railway"
echo "======================================"
echo ""
echo "✅ Code is already pushed to GitHub:"
echo "   https://github.com/riteshgangnani10/sparsh-clinic"
echo ""
echo "Now follow these steps to deploy:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 1: Deploy Backend to Railway"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://railway.app/new"
echo ""
echo "2. Click 'Deploy from GitHub repo'"
echo ""
echo "3. Select: riteshgangnani10/sparsh-clinic"
echo ""
echo "4. Railway will show options. Click 'Add variables'"
echo ""
echo "5. Set Root Directory to: backend"
echo ""
echo "6. Add these environment variables:"
echo ""
echo "   Required (copy-paste these):"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   PORT=5000"
echo "   NODE_ENV=production"
echo "   JWT_SECRET=sparsh-clinic-prod-secret-$(date +%s)-xyz"
echo "   CLOUDINARY_CLOUD_NAME=demo"
echo "   CLOUDINARY_API_KEY=demo"
echo "   CLOUDINARY_API_SECRET=demo"
echo "   EMAIL_HOST=smtp.gmail.com"
echo "   EMAIL_PORT=587"
echo "   EMAIL_USER=demo@example.com"
echo "   EMAIL_PASSWORD=demo"
echo "   EMAIL_FROM=noreply@sparshprc.com"
echo "   EMAIL_TO=sparshprc@gmail.com"
echo "   FRONTEND_URL=http://localhost:3000"
echo "   ADMIN_EMAIL=admin@sparshprc.com"
echo "   ADMIN_PASSWORD=changeThisPassword123!"
echo "   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "7. After deployment starts, click 'New' → 'Database' → 'MongoDB'"
echo ""
echo "8. Once MongoDB is added, copy its connection string"
echo ""
echo "9. Add MONGODB_URI variable to backend service with the connection string"
echo ""
echo "10. Note your backend URL (e.g., sparsh-clinic-backend-production.up.railway.app)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 2: Deploy Frontend to Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "   cd frontend"
echo "   npx vercel --yes"
echo ""
echo "When prompted for environment variables, add:"
echo "   VITE_API_URL=https://YOUR-RAILWAY-BACKEND-URL.railway.app/api"
echo ""
echo "Then deploy to production:"
echo "   npx vercel --prod"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 3: Seed the Database"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After backend is deployed:"
echo ""
echo "   railway login"
echo "   railway link  (select your project)"
echo "   cd backend"
echo "   railway run npm run seed"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 4: Update FRONTEND_URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Railway backend variables, update:"
echo "   FRONTEND_URL=https://your-app.vercel.app"
echo ""
echo "🎉 Done! Your website is now live!"
echo ""
echo "Access it at:"
echo "  - Frontend: https://your-app.vercel.app"
echo "  - Admin: https://your-app.vercel.app/login"
echo "  - Backend API: https://your-backend.railway.app/api"
echo ""
echo "Default login:"
echo "  Email: admin@sparshprc.com"
echo "  Password: changeThisPassword123!"
echo ""

